### PR TITLE
67: implementation of erc20 voting

### PR DESCRIPTION
**Pull request by jac18281828**
adding support for erc20 tokens

### CODE REVIEW

**Comment by dannyadkins** [comment]
Just to understand the scope -- from the code it seems like there's no protection against double-voting with ERC-20, correct? 

Since a user could transfer around tokens since there is no snapshotting/checkpointing

If so, makes sense and seems like it is dependent on the token implementer, but is the plan for us to have a separate CommunityClassERC20Checkpointable that has a different implementation?

**Review by dannyadkins — APPROVED** [review]

**Comment by dannyadkins** [comment]
once you add the methods in CommunityBuilder.sol (if this is planned) I'm happy to help write out some test cases for this as well around double-voting, will be good to have some that we expect to fail

**Comment by jac18281828** [comment]
> Just to understand the scope -- from the code it seems like there's no protection against double-voting with ERC-20, correct?
> 
> Since a user could transfer around tokens since there is no snapshotting/checkpointing
> 
> If so, makes sense and seems like it is dependent on the token implementer, but is the plan for us to have a separate CommunityClassERC20Checkpointable that has a different implementation?

My understanding of the discussion so far has been that we are building a non-transferrable ERC-20 token.    I spoke last week with @rocketmanh and brought up the idea of implementing a transferable ERC-20 with snapshotting capability but he indicated that he wanted to hold off on that.   

If the tokens are non-transferrable we will have no trouble with double voting.  However, I believe we should certainly place a priority on implementing a transferrable token with the ability to take snapshots.  As this will make our contract fairly useless to anyone besides us who is implementing ERC-20 voting.

**Comment by dannyadkins** [comment]
> > Just to understand the scope -- from the code it seems like there's no protection against double-voting with ERC-20, correct?
> > Since a user could transfer around tokens since there is no snapshotting/checkpointing
> > If so, makes sense and seems like it is dependent on the token implementer, but is the plan for us to have a separate CommunityClassERC20Checkpointable that has a different implementation?
> 
> My understanding of the discussion so far has been that we are building a non-transferrable ERC-20 token. I spoke last week with @rocketmanh and brought up the idea of implementing a transferable ERC-20 with snapshotting capability but he indicated that he wanted to hold off on that.
> 
> If the tokens are non-transferrable we will have no trouble with double voting. However, I believe we should certainly place a priority on implementing a transferrable token with the ability to take snapshots. As this will make our contract fairly useless to anyone besides us who is implementing ERC-20 voting.

Gotcha, sounds perfect, didn't realize this was based on the NontransferableERC20 that we made. This should work perfectly in existing implementation then 

Definitely agree that snapshotting is a key next step! But this should work great for how we're launching Revolution v1

**Pull request closed without merging**
